spring:
  application:
    name: consumer-server
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址

server:
  port: 8325

#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
