#nacos版本
#server:
#  port: 6088
#spring:
#  application:
#    name: sidecarpy
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos地址
#sidecar:
#  # 异构微服务的IP
#  ip: 127.0.0.1
#  # 异构微服务的端口
#  port: 3000
#  # 异构微服务的健康检查URL
#  health-check-url: http://localhost:3000/health

#eureka
spring:
  application:
    name: demo-sidecar
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址

#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
sidecar:
  port: 3000
  health-uri: http://localhost:3000/health
#
#ribbon:
#  ConnectTimeout: 50000
#  ReadTimeout: 50000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#
server:
  port: 8326
#
#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    service-url:
#      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
#
#registry:
#  host: localhost
#  port: 31091



